version: "3.0"
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - "db"
    command: ["wait-for-it", "db:27017", "--", "node", "app.js"]
  db:
    image: mongo:4.2.0
    volumes:
      - "mongodata:/data/db"
volumes:
  mongodata:
